from typing import Any, Union, List, Tuple, Optional
import numpy as np

def figure(num: Union[int, str, None] = None, figsize: Tuple[float, float] = None, dpi: float = None, facecolor: str = None, edgecolor: str = None, frameon: bool = True, FigureClass: Any = None, clear: bool = False, **kwargs: Any) -> Any: ...

def plot(*args: Any, scalex: bool = True, scaley: bool = True, data: Any = None, **kwargs: Any) -> List[Any]: ...

def xlabel(xlabel: str, fontdict: Optional[dict] = None, labelpad: Optional[float] = None, **kwargs: Any) -> Any: ...

def ylabel(ylabel: str, fontdict: Optional[dict] = None, labelpad: Optional[float] = None, **kwargs: Any) -> Any: ...

def title(label: str, fontdict: Optional[dict] = None, loc: str = 'center', pad: Optional[float] = None, **kwargs: Any) -> Any: ...

def grid(b: Optional[bool] = None, which: str = 'major', axis: str = 'both', **kwargs: Any) -> None: ...

def savefig(fname: Union[str, Path], dpi: Optional[float] = None, facecolor: str = 'w', edgecolor: str = 'w', orientation: str = 'portrait', papertype: str = None, format: Optional[str] = None, transparent: bool = False, bbox_inches: Optional[Union[str, Tuple[float, float, float, float]]] = None, pad_inches: float = 0.1, frameon: Optional[bool] = None, metadata: Optional[dict] = None) -> None: ...

def close(fig: Optional[Any] = None) -> None: ... 