from typing import Any, Protocol, Union, List, Tuple
import numpy as np

def find_peaks(x: np.ndarray, height: Union[float, Tuple[float, float], None] = None, threshold: Union[float, Tuple[float, float], None] = None, distance: Union[int, None] = None, prominence: Union[float, Tuple[float, float], None] = None, width: Union[float, Tuple[float, float], None] = None, wlen: Union[int, None] = None, rel_height: float = 0.5, plateau_size: Union[int, None] = None) -> Tuple[np.ndarray, dict]: ...

def butter(N: int, Wn: Union[float, List[float]], btype: str = 'low', analog: bool = False, output: str = 'ba', fs: Union[float, None] = None) -> Tuple[np.ndarray, np.ndarray]: ...

def filtfilt(b: np.ndarray, a: np.ndarray, x: np.ndarray, axis: int = -1, padtype: str = 'odd', padlen: Union[int, None] = None, method: str = 'pad', irlen: Union[int, None] = None) -> np.ndarray: ... 